version: '3'
services:
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "88:80"
    depends_on:
      - "db"
    networks:
      - dev-network
    restart: always
  db:
    container_name: "mysql-server"
    image: "mysql:5.6"
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ../backup/:/var/backup
      - ./mysqldata/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - dev-network
    restart: always

networks:
  dev-network: